### PR TITLE
fix: add correct SHA256 & SHA512 sums for heroku-cli

### PR DESCRIPTION
**Pull request by takedawilliam**
Add fix for the following error
```
==> Validating source_x86_64 files with sha256sums...
    heroku-v7.42.13-linux-x64.tar.xz ... FAILED
```

### CODE REVIEW

**Comment by ghost** [comment]
@lbkvu Should .SRCINFO also be updated?

**Comment by robsears** [comment]
[According to Heroku](https://cli-assets.heroku.com/linux-x64), the sha sums should be:

```
{
  "version": "7.42.13",
  "channel": "stable",
  "baseDir": "heroku",
  "gz": "https://cli-assets.heroku.com/heroku-v7.42.13/heroku-v7.42.13-linux-x64.tar.gz",
  "xz": "https://cli-assets.heroku.com/heroku-v7.42.13/heroku-v7.42.13-linux-x64.tar.xz",
  "sha256gz": "51660467e676934020090ebdc92018b80afc80c8fa6adc646fba127fb9aba861",
  "sha256xz": "5eefee051f5295e190f07dff99bb258c42381a200ebd6251a67f103788af285e",
  "node": {
    "compatible": ">=8.3.0",
    "recommended": "12.16.2"
  }
}
```

Where are these other sums coming from? I'm also unclear why/how the tarballs are being served from googleapis.com instead of from Heroku.

**Edit:** Confirmed the sha256xz from Heroku is correct. So the `heroku-v7.42.13-linux-x64.tar.xz` tarball should have these sha sums:

```
sha256xz: 5eefee051f5295e190f07dff99bb258c42381a200ebd6251a67f103788af285e
sha512xz: ade0e45e9751c8aacb8956fbeb8086a6e562dd90fde82cea6ea2cca01b33ed98520239a5e2ea20e5ade5fef0e98e2290b5607cb6c7b71c59d111f944e1eb26ea
```

I downloaded straight from Heroku and updated my PKGBUILD with those sums above and ran `makepkg -si`. All validations passed and the package installed correctly.

**Edit 2:** I was looking for differences in the two tarballs. The main thing is in the package.json files, there is a reference to `"@oclif/plugin-update"` in the Heroku source, but not in the Google source. The Heroku source also has a yarn.lock file while the Google source has a package-lock.json file.

Running `diff -qr` on the unpacked contents of each tarball shows a _ton_ of differences, but these appear to be differences in compiled files. `diff -yt --suppress-common-lines` shows these differences. I haven't done a deep dive into it, but I suspect the oclif plugin and different build tools are the reason the SHA sums differ. Maybe the googleapis source uses a different build pipeline or something.

Still, I don't like that this PKGBUILD downloads from a 3rd party source and has sha sums that differ from the original publisher. That's a pretty big red flag.

**Comment by avery-laird** [comment]
seems very suspicious to me that the tarballs are not coming from Heroku, because I can't see any reason for it. Heroku provides links directly [here.](https://devcenter.heroku.com/articles/heroku-cli#download-and-install)

**Comment by takedawilliam** [comment]
@peterith Thanks for pointing that out. I didn't know .SRCINFO needs to be updated (my first time doing this thing :p)

@robsears Thanks for your detailed explanation. I didn't notice these differences. When updating my system, this package failed due to SHA sums not match, so I only focused on making SHA sums in PKGBUILD file the same as the ones downloaded from this  URL (`https://storage.googleapis.com/arch-package-files/heroku-v$pkgver-linux-x64.tar.xz`)

We have to wait for the original author @SampsonCrowley to explain these differences

**Comment by SampsonCrowley** [comment]
@here sorry guys, I've been out of town for the last 18 hours and had accidentally pushed out some changes without new checksums while I was working with some mobile guys for ARM support. I'll get it updated as soon as I can

**Comment by takedawilliam** [comment]
Original author will fix the issue. This PR is no longer needed

**Comment by SampsonCrowley** [comment]
> seems very suspicious to me that the tarballs are not coming from Heroku, because I can't see any reason for it. Heroku provides links directly [here.](https://devcenter.heroku.com/articles/heroku-cli#download-and-install)

The reason for this is to remove the auto update plugin from the CLI; the Heroku CLI maintainers refuse to accept that there are valid reasons for a package distributed through a build system outside of NPM to decide how updates should be distributed

Now when I release a new version, I compile the Heroku package from source through the same steps their Ubuntu snap uses.

**Comment by SampsonCrowley** [comment]
@here back in town and v7.42.13-3 has the correct sums now

**Comment by SampsonCrowley** [comment]
@here apparently there were still some lingering issues with the checksums in v7.42.13-3; v7.42.13-4 should fix anything still lingering in v7.42.13-3.

@lbkvu would you mind updating to verify all issues have been resolved

**Comment by takedawilliam** [comment]
@SampsonCrowley I still have problem with checksum in your latest commit 1fcf79e0dd400161d67127ba4b89328d9871984b
```
==> Making package: heroku-cli 7.42.13-3 (Fri 11 Sep 2020 06:05:48 PM JST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading heroku-v7.42.13-linux-x64.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.8M  100 18.8M    0     0  3003k      0  0:00:06  0:00:06 --:--:-- 4089k
==> Validating source files with sha256sums...
    heroku-v7.42.13-linux-x64.tar.xz ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by SampsonCrowley** [comment]
@lbkvu that's not v7. 42.13-4

Sorry I meant from the AUR; I guess I never put my last update on github

**Comment by jonhoo** [comment]
> the Heroku CLI maintainers refuse to accept that there are valid reasons for a package distributed through a build system outside of NPM to decide how updates should be distributed

That's very unfortunate :'(
@SampsonCrowley Could you link to the relevant Heroku CLI ticket?

**Comment by SampsonCrowley** [comment]
@jonhoo https://github.com/heroku/cli/issues/129

**Comment by CyberShadow** [comment]
> Now when I release a new version, I compile the Heroku package from source through the same steps their Ubuntu snap uses.

Sorry, but shouldn't this be done by the PKGBUILD script? Isn't this the entire point of PKGBUILD scripts?

The tarball isn't auditable... especially as I see it even comes with a Node binary...

If you are going to package pre-built binaries, I think the package ought to be renamed to have a `-bin` suffix as per AUR guidelines.

**Comment by SampsonCrowley** [comment]
The heroku package always hauls around it's own node binary, even through the old method. This doesn't use the node binary, it's only there because I didn't want to do any modifications other than removing the auto updater. I was trying to keep a package that works for everyone and doesn't update itself. Since it's all javascript, there is no compilation. It's just minification. The build script is in this repo if you like

It was just an easy way to support multiple systems. I forgot that rule when I got carried away trying to adapt. I will return to the old way

**Comment by SampsonCrowley** [comment]
@CyberShadow I moved the compilation process into PKGBUILD#prepare, is that better?

**Comment by CyberShadow** [comment]
Yes, I think that looks much better, thanks!

**Comment by SampsonCrowley** [comment]
@CyberShadow  Glad I can be more standards compliant ☺️

@here also if anyone wants to skip the build times, I also released a `-bin` version that just runs the same #prepare process as this package before release. I also changed it to be hosted through a GitHub Tag instead of my google storage so that you can always view the script that was run to build each version

**Pull request closed without merging**
